version: '3.7'

services:
  php:
    build: docker/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/app:cached
      - ./dockerlive/logs:/var/log

  nginx:
    build: docker/nginx
    restart: always
    expose:
      - '80'
    ports:
      - '81:80'
    depends_on:
      - php
      - db
    volumes:
      - ./app:/var/www/html/app:cached
      - ./dockerlive/logs:/var/log/nginx

  db:
    build: docker/database
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./dockerlive/mysql:/var/lib/mysql